name: Continuous Integration
on:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+.x
    tags:
      - v*
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            !./target/*/*/*.zip
            !./target/*/*/*.tar.gz
          key: cargo-${{ hashFiles('**/Cargo.toml') }}
      - name: Update Rust Toolchain
        run: |
          rustup update stable
          rustup component add rustfmt rust-src clippy
          rustup target add aarch64-apple-darwin
          rustup target add wasm32-unknown-unknown
          cargo install wasm-pack --force
      - name: Install Dependencies
        run: npm install
      - name: Wasm Package
        run: npm run wasm:pack
      - name: Package Extension
        run: npm run package
      - name: Echo Version
        run: echo version=$(node -p  'require('\''./package.json'\'').version') >> $GITHUB_ENV
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: basjoofan vscode ${{ env.version }}
          path: basjoofan-*.vsix
          if-no-files-found: error
      - name: Release Version
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: basjoofan-*.vsix
          draft: true
