name: Continuous Integration
on:
  push:
    branches:
      - master
      - v[0-9]+.[0-9]+.x
    tags:
      - v*
  workflow_dispatch:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install Dependencies
        run: npm install
      - name: Package Extension
        run: npm run package
      - name: Echo Version
        run: echo version=$(node -p  'require('\''./package.json'\'').version') >> $GITHUB_ENV
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: basjoofan vscode ${{ env.version }}
          path: basjoofan-*.vsix
          if-no-files-found: error
      - name: Release Version
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: basjoofan-*.vsix
          draft: true
